name: Run tests

on:
  push:

jobs:
  run-php-tests:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allowFailure }}
    strategy:
      max-parallel: 6
      matrix:
        phpVersions: ['7.4', '8.0']
        winterCmsRelease: ['1.1', 'develop']
        allowFailure: false
        include:
          - winterCmsRelease: develop
            allowFailure: true
      fail-fast: false

    name: PHP ${{ matrix.phpVersions }} - Winter CMS ${{ matrix.winterCmsRelease }}

    steps:
      - name: Checkout changes
        uses: actions/checkout@v2
        with:
          path: twigextensions-plugin

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.phpVersions }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, intl, exif, iconv
          coverage: none

      - name: Install Winter CMS
        run: |
          curl -L https://github.com/wintercms/winter/archive/${{ matrix.winterCmsRelease }}.zip -o ${{ matrix.winterCmsRelease }}.zip -s
          unzip ${{ matrix.winterCmsRelease }}.zip
          rm ${{ matrix.winterCmsRelease }}.zip
          shopt -s dotglob
          mv winter-${{ matrix.winterCmsRelease }}/* ./
          rmdir winter-${{ matrix.winterCmsRelease }}
          shopt -u dotglob
          mkdir -p plugins/creativesizzle
          mv twigextensions-plugin plugins/creativesizzle/twigextensions
          composer config --unset platform.php
          composer install --prefer-dist --no-interaction --no-progress --no-suggest
          composer require --dev php-coveralls/php-coveralls

      - name: Run Linting
        run: ./vendor/bin/parallel-lint plugins/creativesizzle/twigextensions

      - name: Execute tests
        run: |
          cd plugins/creativesizzle/twigextensions
          ../../../vendor/bin/phpunit --coverage-clover build/logs/clover.xml
